### ISSUE TITLE
can not get openid

### ISSUE THREAD

**Issue by ITdakaWGY** [EastWorld/tt-app-mall#3]
你好，我在登陆时遇到can not get openid的情况，请问是哪个地方设置错误了，项目已star

**Comment by gooking** [comment]
1. api工厂后台，左侧菜单系统设置，头条小程序设置的 appid 和 secret 不正确；
2. 项目文件 project.config.json 中的 appid 不正确；
3. config.js 中的 subDomain 不正确；
