### ISSUE TITLE
卡密自动发货时跟微信小程序不同

### ISSUE THREAD

**Issue by ITdakaWGY** [EastWorld/tt-app-mall#4]
设置商品为不使用物流，并设置了卡密自动发货，使用微信小程序购买时，无错误，购买成功后会直接跳转到待收货页面，但是使用头条小程序购买时，跳转到了待发货页面，在后台还要进行发货操作，请问这个地方怎样处理

**Comment by gooking** [comment]
对照着微信小程序版本，自己修改一下
